### ISSUE TITLE
Review ADR 0001 - Record architecture decisions

### ISSUE THREAD

**Issue by mgwalker** [18F/weather.gov#1]
[Draft](https://docs.google.com/document/d/1bXGfwZhwHExUJ24-GW0IRsEpbtNLNU__xo9d3KXSKUg/edit#heading=h.23xodtfgdhr3)

**Comment by colinmurphy01** [comment]
Tomorrow:
- Reviewing ADRs
- Process for recognizing and recording them
- Make sure everyone understands that's what they're for
- Team Agreement on using them

**Comment by mgwalker** [comment]
Closed by #2
