### ISSUE TITLE
We will not use a headless CMS

### ISSUE THREAD

**Issue by mgwalker** [18F/weather.gov#106]
### Context

It's early in the build phase of the project and we are trying to determine what CMS we want to use or if we should build something ourselves. We are [evaluating several options](https://docs.google.com/spreadsheets/d/1SKajxihDa6qzT2Rt3GgJd8PT2B8gDkGZDGO1hK2TwLg/edit#gid=61753279), including traditional CMSes as well as headless CMSes. We've also [documented the difference](https://docs.google.com/document/d/1xJELw4BJ_UzkG9jGTXe0TeKcE4fmkJoDdNe15vrvPng/edit) between the two types of CMS.

### Decision

We will not use a headless CMS because they all, by definition, require that we create the entire frontend, including rendering. While it may not be too difficult technically, it does introduce substantial technical debt and upkeep requirements. A traditional CMS with an existing rendering pipeline we can just plug into should be far more maintainable in the long term.

### Consequences

- We will have fewer options for CMSes.
- Building a single-page app (SPA) frontend would be more difficult. (Note that we are not required to build a SPA, and maybe don't even want to.)

**Comment by colinmurphy01** [comment]
@mgwalker what should we do with this?

**Comment by mgwalker** [comment]
From a project management perspective, I'm not sure! I put it in the backlog because I figured we'd revisit it in a few weeks when/after we've done some prototyping, and I guessed maybe we'd pull it forward into "in progress" when we're ready to make a decision and are working on the language?

From an ADR perspective, I'd argue for keeping it open because it does represent a decision to be made, even if it does not currently capture what we will eventually decide. If that makes sense? Because from my seat, we will make a decision about what kind of CMS to use at some point, and this issue is holding the space for that.

**Comment by colinmurphy01** [comment]
Good clarification. Thank you.

**Comment by mgwalker** [comment]
I don't think this is an isolated decision anymore. It'll likely be part of the decision of what CMS to use, since we're evaluating them in headful and headless modes. Gonna close this; if it turns out this is a standalone decision, we can always reopen it.
