### ISSUE TITLE
How might we layout weather components and use supporting visuals to communicate a comprehensive view of weather for a specific location?

### ISSUE THREAD

**Issue by colinmurphy01** [18F/weather.gov#111]
### Background
We've scoped and/or designed individual components that involve current conditions and the forecast, including

- #34 
- #77 
- #49 
- #110 

These individual components communicate critical individual datapoints for a person to better understand current and impending weather, as a whole they will form a comprehensive summary.

** Related Epic: #55**

### Questions to consider
- We’d like to replace [weather.gov](http://weather.gov/) images with the NOAA icons for usability reasons. However, I don’t want to lose the intended purpose of the images which was gather from public feedback -  and would like to do some discovery and sketching of ways to communicate weather through secondary visuals. - this might be on a layout level
- On a component level, helping to inform and keeping my eyes open for high impact - low maintaince / easy to standardize need for imagery while designing user stories. Ex: imagery/visuals may reinforce and aid in understanding severity/place of weather.

### Related work
- #99 (and how do we represent that on a location page)
- #100 
```[tasklist]
### Tasks
- [ ] Desk research - discovery, wireframes, sketches
- [ ] UX Review
- [ ] Eng Review
```

**Comment by colinmurphy01** [comment]
@janelx I created this ticket based on our slack discussions and based on the points @kmranjo and @sarahmhgov brought up in retro.

**Comment by colinmurphy01** [comment]
I believe we can close this as we move forward with #174, @janelx can you confirm?

**Comment by janelx** [comment]
@colinmurphy01 Yep I can close
