### ISSUE TITLE
Prototype CloudCannon

### ISSUE THREAD

**Issue by colinmurphy01** [18F/weather.gov#132]
CMS prototyping scope is listed in our [CMS strategy doc](https://docs.google.com/document/d/1sgsPErrR_HtVfljt7EK5fWMA8p9f2vKnn4GkRjRfboA/edit#heading=h.ljvidygtuupa).

- [ ] - [ ] Ask Becky to follow up 1) if a gov license already exists 2) reaching out to vendor

**Comment by mgwalker** [comment]
If there's not an existing contract, then we also need to be sure we verify that the EULA is government-compatible, or that a gov-compatible EULA is available.

**Comment by colinmurphy01** [comment]
@cannandev Based on your feature review, prototyping cloudcannon isn't necessary at this time?

**Comment by colinmurphy01** [comment]
We decided to not prototype this headless option with Drupal and Wordpress's options being sufficient for exploration.
