### ISSUE TITLE
Who makes decisions about ATO?

### ISSUE THREAD

**Issue by colinmurphy01** [18F/weather.gov#14]
We need to understand who will sign off on ATO before we launch the new weather.gov. This person will have a lot of influence around other downstream questions such as:

- Are we slotting into an existing boundary or creating a new one?
- Is a lower FISMA category possible?
- What are the risks of lowering FISMA?

We don't need our AO to answer those questions right now, we just need to know who they are so we know who to ask/talk to as those questions become more important, and who we need to be working with along the way to make sure we stay in compliance.

**Comment by mgwalker** [comment]
@mgwalker will email Beckie a heads-up that we'll be in touch

**Comment by mgwalker** [comment]
Beckie thinks Andrew will be our point person, but she'll want to be involved in final decisions around ATO boundaries. She suggests creativity! I'm excited about that.

I propose that we table this topic for a couple weeks until the product team is formalized and we're beyond the path analysis reporting phase. Once we have a formal dedicated product owner (which I know we already do, but it still seems not quite "officially official" until the product team actually kicks off?), they can help us find the right eyeballs to get eyeball with.

**Comment by colinmurphy01** [comment]
Curious what other eyeballs do we need to be involved, we know our PO, CIO, and ISSO? 

Alternative: Do we need to bring in an 18F person to help advise on our options?

**Comment by mgwalker** [comment]
Someone with more expertise on the 18F side might not be a bad idea, tbh. One of the things I'm struggling with is connecting language I understand with language they're using.

**Comment by colinmurphy01** [comment]
Meeting Monday at 1pm EST

**Comment by mgwalker** [comment]
Andrew will be our day-to-day for making sure we're on the right track. NWS will assign an AO based on the FISMA boundary we live inside, which is the new question du jour. We probably can't decide the boundary until we get SLA documentation back from WOC, which is forthcoming.

**Comment by loganmeetsworld** [comment]
Yep let's close it as I think there are better tickets to track.
