### ISSUE TITLE
CMS de-risking strategy document

### ISSUE THREAD

**Issue by cannandev** [18F/weather.gov#20]
document link: [CMS ~~Criteria~~ De-risking Strategy](https://docs.google.com/document/d/1sgsPErrR_HtVfljt7EK5fWMA8p9f2vKnn4GkRjRfboA/edit#heading=h.ljvidygtuupa)

This document is a supplement to the [CMS Comparison spreadsheet](https://docs.google.com/spreadsheets/d/171LhvgSzerrB7Dz-fmDWFWaCvCr0QCYtt1HZOJtIVN0/edit#gid=0), which is ongoing. This supplement categorizes and defines the criteria.

**Comment by colinmurphy01** [comment]
@cannandev when you're back let's talk about this ticket and what needs to be reviewed.
