### ISSUE TITLE
Document Research Plan for MVP phase

### ISSUE THREAD

**Issue by colinmurphy01** [18F/weather.gov#4]
### Background
As we move into the EI phase of prototyping and building an MVP, we need to expand our testing/co-designing activities.
This ticket is an epic to capture the various user research planning activities across three research streams: WFOs, Folks responding to an emergency, Folks experiencing an emergency. 

```[tasklist]
### WFO research
- [ ] https://github.com/18F/weather.gov/issues/24
- [ ] Research plan and design tasks
```
```[tasklist]
### Folks responding in a hazard (partners, community leaders, emergency managers)
- [ ] Write up document for recruitment plan beyond PA participants
- [ ] Design activities
```

```[tasklist]
### Folks experiencing an emergency (General public)
- [ ] PRA for light screener (touchpoints)
- [ ] Design activities
- [ ] https://github.com/18F/weather.gov/issues/25
```

**Comment by colinmurphy01** [comment]
@sarahmhgov created this ticket to track the research plan work. Feel free to edit

**Comment by sarahmhgov** [comment]
thanks and updating to be a research epic!

**Comment by colinmurphy01** [comment]
Debrief from our 1:1 - this Epic should get deprioritized for this sprint and likely is up next

**Comment by colinmurphy01** [comment]
We'll clean up and rescope

**Comment by colinmurphy01** [comment]
@sarahmhgov can you update this. I believe you're doing this via this doc: https://docs.google.com/document/d/1Q9BMLtLG9VC-XHMxQ-4vt8KQRv6UJcqwMKc3qPqdgNM/edit

**Comment by colinmurphy01** [comment]
I believe we have a rough research plan for our MVP phase: https://docs.google.com/document/d/1BbLt5H5x57kLNBqfII_oCdjrypHaudSOTvQ3bq0HFr0/edit#heading=h.nx6o3j63bxdt

So this can be closed
