### ISSUE TITLE
I can understand upcoming long-term weather conditions

### ISSUE THREAD

**Issue by colinmurphy01** [18F/weather.gov#49]
### Background
"Daily weather forecast for next 7 days" was ranked #3 top needs for the public, and #5 for partners. 7-day weather forecast was ranked by 53% of partners and 47% of the public. (Forrester survey)

We heard mostly from partners in our user interviews, but we consistently heard a logical breakdown of time thresholds that are important for planning:
- 1 week before - I want to be aware of a potential hazard
- 72 hr - I want more information on when and where it will land.
 
We heard that the further out prediction models go, the less confident they are ("especially anything beyond 10 days" - Shad)

### Questions to answer
- How far ahead, 7 vs. 10 days is valuable
- What windows are valuable to users (3 vs. 7 or 10 days)
- What level detail is important
- How do we communicate probabilistic considerations (% chance? vs. there's a whole dicussion about this happening around NWS)
- Current examples: hour plot, extended forecast, detailed forecast, weather stories

### Design Considerations
- 7 day:  (less detail)
  - Description of forecast
  - Temp in Fahrenheit
    - High / low temperature
  - Short description of condition
  - Precipitation
    - Probability
    - Type

### Technical Considerations
- What data is accessible via the API vs. manually generated in AWIPS vs. manually configured in the CMS vs. manually generated in a CMS?

### Stakeholder considerations/needs
- TBD

 ### Acceptance Criteria
- TBD

```[tasklist]
### Pebbles and related work
- [ ] have a conversation with a Nashville Meteorologist or Shad? about why it's here what's important
- [ ] consider breaking up into unique stories for discovery
- [ ] Design to identify data that is high value and ??? feasibility to inform Tech investigation
- [ ] #69 
- [ ] #77 
```

**Comment by janelx** [comment]
for quick reference here are the working/work in progress docs

- [Figma wireframes/flow](https://www.figma.com/file/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?type=design&node-id=0-1&mode=design&t=gs8stTpZ7eX49fNm-0)
- [User stories design details](https://docs.google.com/document/d/16W4AN3zjpDpYMzKCrP8K8oprk2-_jF42-FBvC8rdkRY/edit)

**Comment by colinmurphy01** [comment]
Prototyping a github strategy. Apologies for the mix up.

**Comment by janelx** [comment]
**I would like to know for my a specific zip code/city:**
**Forecasts**
- Hourly
- Summary of forecast
- Temp in Fahrenheit
- High / low temperature
- Short description of condition
- Precipitation
- Probability
--Type
**7 day: each day**
**Summary of forecast**
Temp in Fahrenheit
High / low temperature
Short description of condition
Precipitation
Probability
Type


**Forecasters’ short term trends in plain language**

**Comment by colinmurphy01** [comment]
Based on our conversation this afternoon I have updated/created the following tickets for Monday's planning

- #49
- #77 
- #69 
- #75

**Comment by colinmurphy01** [comment]
The component for this is being documented in this ticket #178, this ticket can be closed. Confirm @janelx?
