### ISSUE TITLE
Which CMS options in the market meet our needs and should be prototyped

### ISSUE THREAD

**Issue by cannandev** [18F/weather.gov#7]
### Description
There is a wide variety of Content Management System options in the market. We need to evaluate those options against critical and additional criteria for weather.gov 2.0's compliance and sustainability. 

The goal of this exercise is to identify 2-3 candidates that meet our critical criteria for a prototyping. Prototyping sprints will then evaluate the capabilities and limitations of each platform. 

**Related Boulder: [Boulder]**

```[tasklist]
### Pebbles
- [x] Identify candidates for evaluation
- [x] Identify criteria
- [x] Prioritize criteria
- [x] Evaluate candidates against criteria
- [x] Identify recommended CMS for prototyping
- [x] Present prototype recommendations at Onsite, on Tuesday 7/24
- [x] Related #13
- [x] Decide and commit with Beckie, Andrew, Kolly as accountable individuals
```

### Documents
https://docs.google.com/spreadsheets/d/171LhvgSzerrB7Dz-fmDWFWaCvCr0QCYtt1HZOJtIVN0/edit#gid=0

**Comment by colinmurphy01** [comment]
Updated ticket with details based on our conversations @cannandev and @stacydion let me know if I missed anything.

**Comment by colinmurphy01** [comment]
Deck: https://docs.google.com/presentation/d/16IoPxCN6TsqlyvY-UEGGcDkx1XynotKR5h8cZdvYC1Y/edit#slide=id.g5ecdbbee9e_0_34

**Comment by colinmurphy01** [comment]
We have decided for the PO to own this decision, while keeping champions informed on our progress.
