### ISSUE TITLE
What are the products, initiatives that relate to weather.gov?

### ISSUE THREAD

**Issue by sarahmhgov** [18F/weather.gov#74]
Documentation of products, initiatives to date here: https://docs.google.com/spreadsheets/d/1zbQuNu9KwR6hDWEAGdhWYdGcWD_FSxg1KBluxkF4JTY/edit#gid=0

- [x] Identify initiatives
- [x] Catalogue them and metadata we'd like to have 
- [ ] Fill it out ahead of onsite

**Comment by colinmurphy01** [comment]
Updated to spreadsheet that was shared
