### ISSUE TITLE
beta.weather.gov on the public internet

### ISSUE THREAD

**Issue by colinmurphy01** [18F/weather.gov#93]
### Description
The WOC has issued us a domain name and their routing it through their load balancer directly. The future state is that we have a domain that NWS controls and routes to a different WOC load balancer and forwards to the TIC (TBD) then come back to the same load balancer. 

```[tasklist]
### Tasks
- [x] Request for domain, approved
- [x] Create domain
- [x] Submit NCO ticket (support from Arnold and Steven) - Shad
```

**Comment by colinmurphy01** [comment]
Regroup with Kari on the steps for this

**Comment by mgwalker** [comment]
Keeping this one

**Comment by mgwalker** [comment]
All done!
